// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: findiary/v1/category_service.proto

package v1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/kshku/findiary/backend/internal/api/findiary/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// CategoryServiceName is the fully-qualified name of the CategoryService service.
	CategoryServiceName = "findiary.v1.CategoryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CategoryServiceCreateCategoryProcedure is the fully-qualified name of the CategoryService's
	// CreateCategory RPC.
	CategoryServiceCreateCategoryProcedure = "/findiary.v1.CategoryService/CreateCategory"
	// CategoryServiceGetCategoryProcedure is the fully-qualified name of the CategoryService's
	// GetCategory RPC.
	CategoryServiceGetCategoryProcedure = "/findiary.v1.CategoryService/GetCategory"
	// CategoryServiceUpdateCategoryProcedure is the fully-qualified name of the CategoryService's
	// UpdateCategory RPC.
	CategoryServiceUpdateCategoryProcedure = "/findiary.v1.CategoryService/UpdateCategory"
	// CategoryServiceDeleteCategoryProcedure is the fully-qualified name of the CategoryService's
	// DeleteCategory RPC.
	CategoryServiceDeleteCategoryProcedure = "/findiary.v1.CategoryService/DeleteCategory"
	// CategoryServiceListCategoriesProcedure is the fully-qualified name of the CategoryService's
	// ListCategories RPC.
	CategoryServiceListCategoriesProcedure = "/findiary.v1.CategoryService/ListCategories"
)

// CategoryServiceClient is a client for the findiary.v1.CategoryService service.
type CategoryServiceClient interface {
	CreateCategory(context.Context, *connect_go.Request[v1.CreateCategoryRequest]) (*connect_go.Response[v1.CreateCategoryResponse], error)
	GetCategory(context.Context, *connect_go.Request[v1.GetCategoryRequest]) (*connect_go.Response[v1.GetCategoryResponse], error)
	UpdateCategory(context.Context, *connect_go.Request[v1.UpdateCategoryRequest]) (*connect_go.Response[v1.UpdateCategoryResponse], error)
	DeleteCategory(context.Context, *connect_go.Request[v1.DeleteCategoryRequest]) (*connect_go.Response[v1.DeleteCategoryResponse], error)
	ListCategories(context.Context, *connect_go.Request[v1.ListCategoriesRequest]) (*connect_go.Response[v1.ListCategoriesResponse], error)
}

// NewCategoryServiceClient constructs a client for the findiary.v1.CategoryService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCategoryServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) CategoryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &categoryServiceClient{
		createCategory: connect_go.NewClient[v1.CreateCategoryRequest, v1.CreateCategoryResponse](
			httpClient,
			baseURL+CategoryServiceCreateCategoryProcedure,
			opts...,
		),
		getCategory: connect_go.NewClient[v1.GetCategoryRequest, v1.GetCategoryResponse](
			httpClient,
			baseURL+CategoryServiceGetCategoryProcedure,
			opts...,
		),
		updateCategory: connect_go.NewClient[v1.UpdateCategoryRequest, v1.UpdateCategoryResponse](
			httpClient,
			baseURL+CategoryServiceUpdateCategoryProcedure,
			opts...,
		),
		deleteCategory: connect_go.NewClient[v1.DeleteCategoryRequest, v1.DeleteCategoryResponse](
			httpClient,
			baseURL+CategoryServiceDeleteCategoryProcedure,
			opts...,
		),
		listCategories: connect_go.NewClient[v1.ListCategoriesRequest, v1.ListCategoriesResponse](
			httpClient,
			baseURL+CategoryServiceListCategoriesProcedure,
			opts...,
		),
	}
}

// categoryServiceClient implements CategoryServiceClient.
type categoryServiceClient struct {
	createCategory *connect_go.Client[v1.CreateCategoryRequest, v1.CreateCategoryResponse]
	getCategory    *connect_go.Client[v1.GetCategoryRequest, v1.GetCategoryResponse]
	updateCategory *connect_go.Client[v1.UpdateCategoryRequest, v1.UpdateCategoryResponse]
	deleteCategory *connect_go.Client[v1.DeleteCategoryRequest, v1.DeleteCategoryResponse]
	listCategories *connect_go.Client[v1.ListCategoriesRequest, v1.ListCategoriesResponse]
}

// CreateCategory calls findiary.v1.CategoryService.CreateCategory.
func (c *categoryServiceClient) CreateCategory(ctx context.Context, req *connect_go.Request[v1.CreateCategoryRequest]) (*connect_go.Response[v1.CreateCategoryResponse], error) {
	return c.createCategory.CallUnary(ctx, req)
}

// GetCategory calls findiary.v1.CategoryService.GetCategory.
func (c *categoryServiceClient) GetCategory(ctx context.Context, req *connect_go.Request[v1.GetCategoryRequest]) (*connect_go.Response[v1.GetCategoryResponse], error) {
	return c.getCategory.CallUnary(ctx, req)
}

// UpdateCategory calls findiary.v1.CategoryService.UpdateCategory.
func (c *categoryServiceClient) UpdateCategory(ctx context.Context, req *connect_go.Request[v1.UpdateCategoryRequest]) (*connect_go.Response[v1.UpdateCategoryResponse], error) {
	return c.updateCategory.CallUnary(ctx, req)
}

// DeleteCategory calls findiary.v1.CategoryService.DeleteCategory.
func (c *categoryServiceClient) DeleteCategory(ctx context.Context, req *connect_go.Request[v1.DeleteCategoryRequest]) (*connect_go.Response[v1.DeleteCategoryResponse], error) {
	return c.deleteCategory.CallUnary(ctx, req)
}

// ListCategories calls findiary.v1.CategoryService.ListCategories.
func (c *categoryServiceClient) ListCategories(ctx context.Context, req *connect_go.Request[v1.ListCategoriesRequest]) (*connect_go.Response[v1.ListCategoriesResponse], error) {
	return c.listCategories.CallUnary(ctx, req)
}

// CategoryServiceHandler is an implementation of the findiary.v1.CategoryService service.
type CategoryServiceHandler interface {
	CreateCategory(context.Context, *connect_go.Request[v1.CreateCategoryRequest]) (*connect_go.Response[v1.CreateCategoryResponse], error)
	GetCategory(context.Context, *connect_go.Request[v1.GetCategoryRequest]) (*connect_go.Response[v1.GetCategoryResponse], error)
	UpdateCategory(context.Context, *connect_go.Request[v1.UpdateCategoryRequest]) (*connect_go.Response[v1.UpdateCategoryResponse], error)
	DeleteCategory(context.Context, *connect_go.Request[v1.DeleteCategoryRequest]) (*connect_go.Response[v1.DeleteCategoryResponse], error)
	ListCategories(context.Context, *connect_go.Request[v1.ListCategoriesRequest]) (*connect_go.Response[v1.ListCategoriesResponse], error)
}

// NewCategoryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCategoryServiceHandler(svc CategoryServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	categoryServiceCreateCategoryHandler := connect_go.NewUnaryHandler(
		CategoryServiceCreateCategoryProcedure,
		svc.CreateCategory,
		opts...,
	)
	categoryServiceGetCategoryHandler := connect_go.NewUnaryHandler(
		CategoryServiceGetCategoryProcedure,
		svc.GetCategory,
		opts...,
	)
	categoryServiceUpdateCategoryHandler := connect_go.NewUnaryHandler(
		CategoryServiceUpdateCategoryProcedure,
		svc.UpdateCategory,
		opts...,
	)
	categoryServiceDeleteCategoryHandler := connect_go.NewUnaryHandler(
		CategoryServiceDeleteCategoryProcedure,
		svc.DeleteCategory,
		opts...,
	)
	categoryServiceListCategoriesHandler := connect_go.NewUnaryHandler(
		CategoryServiceListCategoriesProcedure,
		svc.ListCategories,
		opts...,
	)
	return "/findiary.v1.CategoryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CategoryServiceCreateCategoryProcedure:
			categoryServiceCreateCategoryHandler.ServeHTTP(w, r)
		case CategoryServiceGetCategoryProcedure:
			categoryServiceGetCategoryHandler.ServeHTTP(w, r)
		case CategoryServiceUpdateCategoryProcedure:
			categoryServiceUpdateCategoryHandler.ServeHTTP(w, r)
		case CategoryServiceDeleteCategoryProcedure:
			categoryServiceDeleteCategoryHandler.ServeHTTP(w, r)
		case CategoryServiceListCategoriesProcedure:
			categoryServiceListCategoriesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCategoryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCategoryServiceHandler struct{}

func (UnimplementedCategoryServiceHandler) CreateCategory(context.Context, *connect_go.Request[v1.CreateCategoryRequest]) (*connect_go.Response[v1.CreateCategoryResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.CategoryService.CreateCategory is not implemented"))
}

func (UnimplementedCategoryServiceHandler) GetCategory(context.Context, *connect_go.Request[v1.GetCategoryRequest]) (*connect_go.Response[v1.GetCategoryResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.CategoryService.GetCategory is not implemented"))
}

func (UnimplementedCategoryServiceHandler) UpdateCategory(context.Context, *connect_go.Request[v1.UpdateCategoryRequest]) (*connect_go.Response[v1.UpdateCategoryResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.CategoryService.UpdateCategory is not implemented"))
}

func (UnimplementedCategoryServiceHandler) DeleteCategory(context.Context, *connect_go.Request[v1.DeleteCategoryRequest]) (*connect_go.Response[v1.DeleteCategoryResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.CategoryService.DeleteCategory is not implemented"))
}

func (UnimplementedCategoryServiceHandler) ListCategories(context.Context, *connect_go.Request[v1.ListCategoriesRequest]) (*connect_go.Response[v1.ListCategoriesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.CategoryService.ListCategories is not implemented"))
}
