// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: findiary/v1/dashboard_service.proto

package v1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/kshku/findiary/backend/internal/api/findiary/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// DashboardServiceName is the fully-qualified name of the DashboardService service.
	DashboardServiceName = "findiary.v1.DashboardService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DashboardServiceGetDashboardProcedure is the fully-qualified name of the DashboardService's
	// GetDashboard RPC.
	DashboardServiceGetDashboardProcedure = "/findiary.v1.DashboardService/GetDashboard"
)

// DashboardServiceClient is a client for the findiary.v1.DashboardService service.
type DashboardServiceClient interface {
	GetDashboard(context.Context, *connect_go.Request[v1.GetDashboardRequest]) (*connect_go.Response[v1.GetDashboardResponse], error)
}

// NewDashboardServiceClient constructs a client for the findiary.v1.DashboardService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDashboardServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) DashboardServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &dashboardServiceClient{
		getDashboard: connect_go.NewClient[v1.GetDashboardRequest, v1.GetDashboardResponse](
			httpClient,
			baseURL+DashboardServiceGetDashboardProcedure,
			opts...,
		),
	}
}

// dashboardServiceClient implements DashboardServiceClient.
type dashboardServiceClient struct {
	getDashboard *connect_go.Client[v1.GetDashboardRequest, v1.GetDashboardResponse]
}

// GetDashboard calls findiary.v1.DashboardService.GetDashboard.
func (c *dashboardServiceClient) GetDashboard(ctx context.Context, req *connect_go.Request[v1.GetDashboardRequest]) (*connect_go.Response[v1.GetDashboardResponse], error) {
	return c.getDashboard.CallUnary(ctx, req)
}

// DashboardServiceHandler is an implementation of the findiary.v1.DashboardService service.
type DashboardServiceHandler interface {
	GetDashboard(context.Context, *connect_go.Request[v1.GetDashboardRequest]) (*connect_go.Response[v1.GetDashboardResponse], error)
}

// NewDashboardServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDashboardServiceHandler(svc DashboardServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	dashboardServiceGetDashboardHandler := connect_go.NewUnaryHandler(
		DashboardServiceGetDashboardProcedure,
		svc.GetDashboard,
		opts...,
	)
	return "/findiary.v1.DashboardService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DashboardServiceGetDashboardProcedure:
			dashboardServiceGetDashboardHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDashboardServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDashboardServiceHandler struct{}

func (UnimplementedDashboardServiceHandler) GetDashboard(context.Context, *connect_go.Request[v1.GetDashboardRequest]) (*connect_go.Response[v1.GetDashboardResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.DashboardService.GetDashboard is not implemented"))
}
