// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: findiary/v1/family_service.proto

package v1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/kshku/findiary/backend/internal/api/findiary/v1"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// FamilyServiceName is the fully-qualified name of the FamilyService service.
	FamilyServiceName = "findiary.v1.FamilyService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FamilyServiceCreateFamilyProcedure is the fully-qualified name of the FamilyService's
	// CreateFamily RPC.
	FamilyServiceCreateFamilyProcedure = "/findiary.v1.FamilyService/CreateFamily"
	// FamilyServiceGetFamilyProcedure is the fully-qualified name of the FamilyService's GetFamily RPC.
	FamilyServiceGetFamilyProcedure = "/findiary.v1.FamilyService/GetFamily"
	// FamilyServiceUpdateFamilyProcedure is the fully-qualified name of the FamilyService's
	// UpdateFamily RPC.
	FamilyServiceUpdateFamilyProcedure = "/findiary.v1.FamilyService/UpdateFamily"
	// FamilyServiceListMyFamiliesProcedure is the fully-qualified name of the FamilyService's
	// ListMyFamilies RPC.
	FamilyServiceListMyFamiliesProcedure = "/findiary.v1.FamilyService/ListMyFamilies"
	// FamilyServiceAddMemberProcedure is the fully-qualified name of the FamilyService's AddMember RPC.
	FamilyServiceAddMemberProcedure = "/findiary.v1.FamilyService/AddMember"
	// FamilyServiceRemoveMemberProcedure is the fully-qualified name of the FamilyService's
	// RemoveMember RPC.
	FamilyServiceRemoveMemberProcedure = "/findiary.v1.FamilyService/RemoveMember"
	// FamilyServiceInviteMemberProcedure is the fully-qualified name of the FamilyService's
	// InviteMember RPC.
	FamilyServiceInviteMemberProcedure = "/findiary.v1.FamilyService/InviteMember"
	// FamilyServiceAcceptInvitationProcedure is the fully-qualified name of the FamilyService's
	// AcceptInvitation RPC.
	FamilyServiceAcceptInvitationProcedure = "/findiary.v1.FamilyService/AcceptInvitation"
	// FamilyServiceRevokeInvitationProcedure is the fully-qualified name of the FamilyService's
	// RevokeInvitation RPC.
	FamilyServiceRevokeInvitationProcedure = "/findiary.v1.FamilyService/RevokeInvitation"
	// FamilyServiceListInvitationsProcedure is the fully-qualified name of the FamilyService's
	// ListInvitations RPC.
	FamilyServiceListInvitationsProcedure = "/findiary.v1.FamilyService/ListInvitations"
	// FamilyServiceListMembersProcedure is the fully-qualified name of the FamilyService's ListMembers
	// RPC.
	FamilyServiceListMembersProcedure = "/findiary.v1.FamilyService/ListMembers"
)

// FamilyServiceClient is a client for the findiary.v1.FamilyService service.
type FamilyServiceClient interface {
	CreateFamily(context.Context, *connect_go.Request[v1.CreateFamilyRequest]) (*connect_go.Response[v1.CreateFamilyResponse], error)
	GetFamily(context.Context, *connect_go.Request[v1.GetFamilyRequest]) (*connect_go.Response[v1.GetFamilyResponse], error)
	UpdateFamily(context.Context, *connect_go.Request[v1.UpdateFamilyRequest]) (*connect_go.Response[v1.UpdateFamilyResponse], error)
	ListMyFamilies(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.ListMyFamiliesResponse], error)
	AddMember(context.Context, *connect_go.Request[v1.AddMemberRequest]) (*connect_go.Response[v1.AddMemberResponse], error)
	RemoveMember(context.Context, *connect_go.Request[v1.RemoveMemberRequest]) (*connect_go.Response[v1.RemoveMemberResponse], error)
	InviteMember(context.Context, *connect_go.Request[v1.InviteMemberRequest]) (*connect_go.Response[v1.InviteMemberResponse], error)
	AcceptInvitation(context.Context, *connect_go.Request[v1.AcceptInvitationRequest]) (*connect_go.Response[v1.AcceptInvitationResponse], error)
	RevokeInvitation(context.Context, *connect_go.Request[v1.RevokeInvitationRequest]) (*connect_go.Response[v1.RevokeInvitationResponse], error)
	ListInvitations(context.Context, *connect_go.Request[v1.ListInvitationsRequest]) (*connect_go.Response[v1.ListInvitationsResponse], error)
	ListMembers(context.Context, *connect_go.Request[v1.ListMembersRequest]) (*connect_go.Response[v1.ListMembersResponse], error)
}

// NewFamilyServiceClient constructs a client for the findiary.v1.FamilyService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFamilyServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) FamilyServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &familyServiceClient{
		createFamily: connect_go.NewClient[v1.CreateFamilyRequest, v1.CreateFamilyResponse](
			httpClient,
			baseURL+FamilyServiceCreateFamilyProcedure,
			opts...,
		),
		getFamily: connect_go.NewClient[v1.GetFamilyRequest, v1.GetFamilyResponse](
			httpClient,
			baseURL+FamilyServiceGetFamilyProcedure,
			opts...,
		),
		updateFamily: connect_go.NewClient[v1.UpdateFamilyRequest, v1.UpdateFamilyResponse](
			httpClient,
			baseURL+FamilyServiceUpdateFamilyProcedure,
			opts...,
		),
		listMyFamilies: connect_go.NewClient[emptypb.Empty, v1.ListMyFamiliesResponse](
			httpClient,
			baseURL+FamilyServiceListMyFamiliesProcedure,
			opts...,
		),
		addMember: connect_go.NewClient[v1.AddMemberRequest, v1.AddMemberResponse](
			httpClient,
			baseURL+FamilyServiceAddMemberProcedure,
			opts...,
		),
		removeMember: connect_go.NewClient[v1.RemoveMemberRequest, v1.RemoveMemberResponse](
			httpClient,
			baseURL+FamilyServiceRemoveMemberProcedure,
			opts...,
		),
		inviteMember: connect_go.NewClient[v1.InviteMemberRequest, v1.InviteMemberResponse](
			httpClient,
			baseURL+FamilyServiceInviteMemberProcedure,
			opts...,
		),
		acceptInvitation: connect_go.NewClient[v1.AcceptInvitationRequest, v1.AcceptInvitationResponse](
			httpClient,
			baseURL+FamilyServiceAcceptInvitationProcedure,
			opts...,
		),
		revokeInvitation: connect_go.NewClient[v1.RevokeInvitationRequest, v1.RevokeInvitationResponse](
			httpClient,
			baseURL+FamilyServiceRevokeInvitationProcedure,
			opts...,
		),
		listInvitations: connect_go.NewClient[v1.ListInvitationsRequest, v1.ListInvitationsResponse](
			httpClient,
			baseURL+FamilyServiceListInvitationsProcedure,
			opts...,
		),
		listMembers: connect_go.NewClient[v1.ListMembersRequest, v1.ListMembersResponse](
			httpClient,
			baseURL+FamilyServiceListMembersProcedure,
			opts...,
		),
	}
}

// familyServiceClient implements FamilyServiceClient.
type familyServiceClient struct {
	createFamily     *connect_go.Client[v1.CreateFamilyRequest, v1.CreateFamilyResponse]
	getFamily        *connect_go.Client[v1.GetFamilyRequest, v1.GetFamilyResponse]
	updateFamily     *connect_go.Client[v1.UpdateFamilyRequest, v1.UpdateFamilyResponse]
	listMyFamilies   *connect_go.Client[emptypb.Empty, v1.ListMyFamiliesResponse]
	addMember        *connect_go.Client[v1.AddMemberRequest, v1.AddMemberResponse]
	removeMember     *connect_go.Client[v1.RemoveMemberRequest, v1.RemoveMemberResponse]
	inviteMember     *connect_go.Client[v1.InviteMemberRequest, v1.InviteMemberResponse]
	acceptInvitation *connect_go.Client[v1.AcceptInvitationRequest, v1.AcceptInvitationResponse]
	revokeInvitation *connect_go.Client[v1.RevokeInvitationRequest, v1.RevokeInvitationResponse]
	listInvitations  *connect_go.Client[v1.ListInvitationsRequest, v1.ListInvitationsResponse]
	listMembers      *connect_go.Client[v1.ListMembersRequest, v1.ListMembersResponse]
}

// CreateFamily calls findiary.v1.FamilyService.CreateFamily.
func (c *familyServiceClient) CreateFamily(ctx context.Context, req *connect_go.Request[v1.CreateFamilyRequest]) (*connect_go.Response[v1.CreateFamilyResponse], error) {
	return c.createFamily.CallUnary(ctx, req)
}

// GetFamily calls findiary.v1.FamilyService.GetFamily.
func (c *familyServiceClient) GetFamily(ctx context.Context, req *connect_go.Request[v1.GetFamilyRequest]) (*connect_go.Response[v1.GetFamilyResponse], error) {
	return c.getFamily.CallUnary(ctx, req)
}

// UpdateFamily calls findiary.v1.FamilyService.UpdateFamily.
func (c *familyServiceClient) UpdateFamily(ctx context.Context, req *connect_go.Request[v1.UpdateFamilyRequest]) (*connect_go.Response[v1.UpdateFamilyResponse], error) {
	return c.updateFamily.CallUnary(ctx, req)
}

// ListMyFamilies calls findiary.v1.FamilyService.ListMyFamilies.
func (c *familyServiceClient) ListMyFamilies(ctx context.Context, req *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.ListMyFamiliesResponse], error) {
	return c.listMyFamilies.CallUnary(ctx, req)
}

// AddMember calls findiary.v1.FamilyService.AddMember.
func (c *familyServiceClient) AddMember(ctx context.Context, req *connect_go.Request[v1.AddMemberRequest]) (*connect_go.Response[v1.AddMemberResponse], error) {
	return c.addMember.CallUnary(ctx, req)
}

// RemoveMember calls findiary.v1.FamilyService.RemoveMember.
func (c *familyServiceClient) RemoveMember(ctx context.Context, req *connect_go.Request[v1.RemoveMemberRequest]) (*connect_go.Response[v1.RemoveMemberResponse], error) {
	return c.removeMember.CallUnary(ctx, req)
}

// InviteMember calls findiary.v1.FamilyService.InviteMember.
func (c *familyServiceClient) InviteMember(ctx context.Context, req *connect_go.Request[v1.InviteMemberRequest]) (*connect_go.Response[v1.InviteMemberResponse], error) {
	return c.inviteMember.CallUnary(ctx, req)
}

// AcceptInvitation calls findiary.v1.FamilyService.AcceptInvitation.
func (c *familyServiceClient) AcceptInvitation(ctx context.Context, req *connect_go.Request[v1.AcceptInvitationRequest]) (*connect_go.Response[v1.AcceptInvitationResponse], error) {
	return c.acceptInvitation.CallUnary(ctx, req)
}

// RevokeInvitation calls findiary.v1.FamilyService.RevokeInvitation.
func (c *familyServiceClient) RevokeInvitation(ctx context.Context, req *connect_go.Request[v1.RevokeInvitationRequest]) (*connect_go.Response[v1.RevokeInvitationResponse], error) {
	return c.revokeInvitation.CallUnary(ctx, req)
}

// ListInvitations calls findiary.v1.FamilyService.ListInvitations.
func (c *familyServiceClient) ListInvitations(ctx context.Context, req *connect_go.Request[v1.ListInvitationsRequest]) (*connect_go.Response[v1.ListInvitationsResponse], error) {
	return c.listInvitations.CallUnary(ctx, req)
}

// ListMembers calls findiary.v1.FamilyService.ListMembers.
func (c *familyServiceClient) ListMembers(ctx context.Context, req *connect_go.Request[v1.ListMembersRequest]) (*connect_go.Response[v1.ListMembersResponse], error) {
	return c.listMembers.CallUnary(ctx, req)
}

// FamilyServiceHandler is an implementation of the findiary.v1.FamilyService service.
type FamilyServiceHandler interface {
	CreateFamily(context.Context, *connect_go.Request[v1.CreateFamilyRequest]) (*connect_go.Response[v1.CreateFamilyResponse], error)
	GetFamily(context.Context, *connect_go.Request[v1.GetFamilyRequest]) (*connect_go.Response[v1.GetFamilyResponse], error)
	UpdateFamily(context.Context, *connect_go.Request[v1.UpdateFamilyRequest]) (*connect_go.Response[v1.UpdateFamilyResponse], error)
	ListMyFamilies(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.ListMyFamiliesResponse], error)
	AddMember(context.Context, *connect_go.Request[v1.AddMemberRequest]) (*connect_go.Response[v1.AddMemberResponse], error)
	RemoveMember(context.Context, *connect_go.Request[v1.RemoveMemberRequest]) (*connect_go.Response[v1.RemoveMemberResponse], error)
	InviteMember(context.Context, *connect_go.Request[v1.InviteMemberRequest]) (*connect_go.Response[v1.InviteMemberResponse], error)
	AcceptInvitation(context.Context, *connect_go.Request[v1.AcceptInvitationRequest]) (*connect_go.Response[v1.AcceptInvitationResponse], error)
	RevokeInvitation(context.Context, *connect_go.Request[v1.RevokeInvitationRequest]) (*connect_go.Response[v1.RevokeInvitationResponse], error)
	ListInvitations(context.Context, *connect_go.Request[v1.ListInvitationsRequest]) (*connect_go.Response[v1.ListInvitationsResponse], error)
	ListMembers(context.Context, *connect_go.Request[v1.ListMembersRequest]) (*connect_go.Response[v1.ListMembersResponse], error)
}

// NewFamilyServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFamilyServiceHandler(svc FamilyServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	familyServiceCreateFamilyHandler := connect_go.NewUnaryHandler(
		FamilyServiceCreateFamilyProcedure,
		svc.CreateFamily,
		opts...,
	)
	familyServiceGetFamilyHandler := connect_go.NewUnaryHandler(
		FamilyServiceGetFamilyProcedure,
		svc.GetFamily,
		opts...,
	)
	familyServiceUpdateFamilyHandler := connect_go.NewUnaryHandler(
		FamilyServiceUpdateFamilyProcedure,
		svc.UpdateFamily,
		opts...,
	)
	familyServiceListMyFamiliesHandler := connect_go.NewUnaryHandler(
		FamilyServiceListMyFamiliesProcedure,
		svc.ListMyFamilies,
		opts...,
	)
	familyServiceAddMemberHandler := connect_go.NewUnaryHandler(
		FamilyServiceAddMemberProcedure,
		svc.AddMember,
		opts...,
	)
	familyServiceRemoveMemberHandler := connect_go.NewUnaryHandler(
		FamilyServiceRemoveMemberProcedure,
		svc.RemoveMember,
		opts...,
	)
	familyServiceInviteMemberHandler := connect_go.NewUnaryHandler(
		FamilyServiceInviteMemberProcedure,
		svc.InviteMember,
		opts...,
	)
	familyServiceAcceptInvitationHandler := connect_go.NewUnaryHandler(
		FamilyServiceAcceptInvitationProcedure,
		svc.AcceptInvitation,
		opts...,
	)
	familyServiceRevokeInvitationHandler := connect_go.NewUnaryHandler(
		FamilyServiceRevokeInvitationProcedure,
		svc.RevokeInvitation,
		opts...,
	)
	familyServiceListInvitationsHandler := connect_go.NewUnaryHandler(
		FamilyServiceListInvitationsProcedure,
		svc.ListInvitations,
		opts...,
	)
	familyServiceListMembersHandler := connect_go.NewUnaryHandler(
		FamilyServiceListMembersProcedure,
		svc.ListMembers,
		opts...,
	)
	return "/findiary.v1.FamilyService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FamilyServiceCreateFamilyProcedure:
			familyServiceCreateFamilyHandler.ServeHTTP(w, r)
		case FamilyServiceGetFamilyProcedure:
			familyServiceGetFamilyHandler.ServeHTTP(w, r)
		case FamilyServiceUpdateFamilyProcedure:
			familyServiceUpdateFamilyHandler.ServeHTTP(w, r)
		case FamilyServiceListMyFamiliesProcedure:
			familyServiceListMyFamiliesHandler.ServeHTTP(w, r)
		case FamilyServiceAddMemberProcedure:
			familyServiceAddMemberHandler.ServeHTTP(w, r)
		case FamilyServiceRemoveMemberProcedure:
			familyServiceRemoveMemberHandler.ServeHTTP(w, r)
		case FamilyServiceInviteMemberProcedure:
			familyServiceInviteMemberHandler.ServeHTTP(w, r)
		case FamilyServiceAcceptInvitationProcedure:
			familyServiceAcceptInvitationHandler.ServeHTTP(w, r)
		case FamilyServiceRevokeInvitationProcedure:
			familyServiceRevokeInvitationHandler.ServeHTTP(w, r)
		case FamilyServiceListInvitationsProcedure:
			familyServiceListInvitationsHandler.ServeHTTP(w, r)
		case FamilyServiceListMembersProcedure:
			familyServiceListMembersHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFamilyServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFamilyServiceHandler struct{}

func (UnimplementedFamilyServiceHandler) CreateFamily(context.Context, *connect_go.Request[v1.CreateFamilyRequest]) (*connect_go.Response[v1.CreateFamilyResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.FamilyService.CreateFamily is not implemented"))
}

func (UnimplementedFamilyServiceHandler) GetFamily(context.Context, *connect_go.Request[v1.GetFamilyRequest]) (*connect_go.Response[v1.GetFamilyResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.FamilyService.GetFamily is not implemented"))
}

func (UnimplementedFamilyServiceHandler) UpdateFamily(context.Context, *connect_go.Request[v1.UpdateFamilyRequest]) (*connect_go.Response[v1.UpdateFamilyResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.FamilyService.UpdateFamily is not implemented"))
}

func (UnimplementedFamilyServiceHandler) ListMyFamilies(context.Context, *connect_go.Request[emptypb.Empty]) (*connect_go.Response[v1.ListMyFamiliesResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.FamilyService.ListMyFamilies is not implemented"))
}

func (UnimplementedFamilyServiceHandler) AddMember(context.Context, *connect_go.Request[v1.AddMemberRequest]) (*connect_go.Response[v1.AddMemberResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.FamilyService.AddMember is not implemented"))
}

func (UnimplementedFamilyServiceHandler) RemoveMember(context.Context, *connect_go.Request[v1.RemoveMemberRequest]) (*connect_go.Response[v1.RemoveMemberResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.FamilyService.RemoveMember is not implemented"))
}

func (UnimplementedFamilyServiceHandler) InviteMember(context.Context, *connect_go.Request[v1.InviteMemberRequest]) (*connect_go.Response[v1.InviteMemberResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.FamilyService.InviteMember is not implemented"))
}

func (UnimplementedFamilyServiceHandler) AcceptInvitation(context.Context, *connect_go.Request[v1.AcceptInvitationRequest]) (*connect_go.Response[v1.AcceptInvitationResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.FamilyService.AcceptInvitation is not implemented"))
}

func (UnimplementedFamilyServiceHandler) RevokeInvitation(context.Context, *connect_go.Request[v1.RevokeInvitationRequest]) (*connect_go.Response[v1.RevokeInvitationResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.FamilyService.RevokeInvitation is not implemented"))
}

func (UnimplementedFamilyServiceHandler) ListInvitations(context.Context, *connect_go.Request[v1.ListInvitationsRequest]) (*connect_go.Response[v1.ListInvitationsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.FamilyService.ListInvitations is not implemented"))
}

func (UnimplementedFamilyServiceHandler) ListMembers(context.Context, *connect_go.Request[v1.ListMembersRequest]) (*connect_go.Response[v1.ListMembersResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.FamilyService.ListMembers is not implemented"))
}
