// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: findiary/v1/transaction_service.proto

package v1connect

import (
	context "context"
	errors "errors"
	connect_go "github.com/bufbuild/connect-go"
	v1 "github.com/kshku/findiary/backend/internal/api/findiary/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect_go.IsAtLeastVersion0_1_0

const (
	// TransactionServiceName is the fully-qualified name of the TransactionService service.
	TransactionServiceName = "findiary.v1.TransactionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TransactionServiceCreateTransactionProcedure is the fully-qualified name of the
	// TransactionService's CreateTransaction RPC.
	TransactionServiceCreateTransactionProcedure = "/findiary.v1.TransactionService/CreateTransaction"
	// TransactionServiceGetTransactionProcedure is the fully-qualified name of the TransactionService's
	// GetTransaction RPC.
	TransactionServiceGetTransactionProcedure = "/findiary.v1.TransactionService/GetTransaction"
	// TransactionServiceUpdateTransactionProcedure is the fully-qualified name of the
	// TransactionService's UpdateTransaction RPC.
	TransactionServiceUpdateTransactionProcedure = "/findiary.v1.TransactionService/UpdateTransaction"
	// TransactionServiceDeleteTransactionProcedure is the fully-qualified name of the
	// TransactionService's DeleteTransaction RPC.
	TransactionServiceDeleteTransactionProcedure = "/findiary.v1.TransactionService/DeleteTransaction"
	// TransactionServiceListTransactionsProcedure is the fully-qualified name of the
	// TransactionService's ListTransactions RPC.
	TransactionServiceListTransactionsProcedure = "/findiary.v1.TransactionService/ListTransactions"
)

// TransactionServiceClient is a client for the findiary.v1.TransactionService service.
type TransactionServiceClient interface {
	CreateTransaction(context.Context, *connect_go.Request[v1.CreateTransactionRequest]) (*connect_go.Response[v1.CreateTransactionResponse], error)
	GetTransaction(context.Context, *connect_go.Request[v1.GetTransactionRequest]) (*connect_go.Response[v1.GetTransactionResponse], error)
	UpdateTransaction(context.Context, *connect_go.Request[v1.UpdateTransactionRequest]) (*connect_go.Response[v1.UpdateTransactionResponse], error)
	DeleteTransaction(context.Context, *connect_go.Request[v1.DeleteTransactionRequest]) (*connect_go.Response[v1.DeleteTransactionResponse], error)
	ListTransactions(context.Context, *connect_go.Request[v1.ListTransactionsRequest]) (*connect_go.Response[v1.ListTransactionsResponse], error)
}

// NewTransactionServiceClient constructs a client for the findiary.v1.TransactionService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTransactionServiceClient(httpClient connect_go.HTTPClient, baseURL string, opts ...connect_go.ClientOption) TransactionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &transactionServiceClient{
		createTransaction: connect_go.NewClient[v1.CreateTransactionRequest, v1.CreateTransactionResponse](
			httpClient,
			baseURL+TransactionServiceCreateTransactionProcedure,
			opts...,
		),
		getTransaction: connect_go.NewClient[v1.GetTransactionRequest, v1.GetTransactionResponse](
			httpClient,
			baseURL+TransactionServiceGetTransactionProcedure,
			opts...,
		),
		updateTransaction: connect_go.NewClient[v1.UpdateTransactionRequest, v1.UpdateTransactionResponse](
			httpClient,
			baseURL+TransactionServiceUpdateTransactionProcedure,
			opts...,
		),
		deleteTransaction: connect_go.NewClient[v1.DeleteTransactionRequest, v1.DeleteTransactionResponse](
			httpClient,
			baseURL+TransactionServiceDeleteTransactionProcedure,
			opts...,
		),
		listTransactions: connect_go.NewClient[v1.ListTransactionsRequest, v1.ListTransactionsResponse](
			httpClient,
			baseURL+TransactionServiceListTransactionsProcedure,
			opts...,
		),
	}
}

// transactionServiceClient implements TransactionServiceClient.
type transactionServiceClient struct {
	createTransaction *connect_go.Client[v1.CreateTransactionRequest, v1.CreateTransactionResponse]
	getTransaction    *connect_go.Client[v1.GetTransactionRequest, v1.GetTransactionResponse]
	updateTransaction *connect_go.Client[v1.UpdateTransactionRequest, v1.UpdateTransactionResponse]
	deleteTransaction *connect_go.Client[v1.DeleteTransactionRequest, v1.DeleteTransactionResponse]
	listTransactions  *connect_go.Client[v1.ListTransactionsRequest, v1.ListTransactionsResponse]
}

// CreateTransaction calls findiary.v1.TransactionService.CreateTransaction.
func (c *transactionServiceClient) CreateTransaction(ctx context.Context, req *connect_go.Request[v1.CreateTransactionRequest]) (*connect_go.Response[v1.CreateTransactionResponse], error) {
	return c.createTransaction.CallUnary(ctx, req)
}

// GetTransaction calls findiary.v1.TransactionService.GetTransaction.
func (c *transactionServiceClient) GetTransaction(ctx context.Context, req *connect_go.Request[v1.GetTransactionRequest]) (*connect_go.Response[v1.GetTransactionResponse], error) {
	return c.getTransaction.CallUnary(ctx, req)
}

// UpdateTransaction calls findiary.v1.TransactionService.UpdateTransaction.
func (c *transactionServiceClient) UpdateTransaction(ctx context.Context, req *connect_go.Request[v1.UpdateTransactionRequest]) (*connect_go.Response[v1.UpdateTransactionResponse], error) {
	return c.updateTransaction.CallUnary(ctx, req)
}

// DeleteTransaction calls findiary.v1.TransactionService.DeleteTransaction.
func (c *transactionServiceClient) DeleteTransaction(ctx context.Context, req *connect_go.Request[v1.DeleteTransactionRequest]) (*connect_go.Response[v1.DeleteTransactionResponse], error) {
	return c.deleteTransaction.CallUnary(ctx, req)
}

// ListTransactions calls findiary.v1.TransactionService.ListTransactions.
func (c *transactionServiceClient) ListTransactions(ctx context.Context, req *connect_go.Request[v1.ListTransactionsRequest]) (*connect_go.Response[v1.ListTransactionsResponse], error) {
	return c.listTransactions.CallUnary(ctx, req)
}

// TransactionServiceHandler is an implementation of the findiary.v1.TransactionService service.
type TransactionServiceHandler interface {
	CreateTransaction(context.Context, *connect_go.Request[v1.CreateTransactionRequest]) (*connect_go.Response[v1.CreateTransactionResponse], error)
	GetTransaction(context.Context, *connect_go.Request[v1.GetTransactionRequest]) (*connect_go.Response[v1.GetTransactionResponse], error)
	UpdateTransaction(context.Context, *connect_go.Request[v1.UpdateTransactionRequest]) (*connect_go.Response[v1.UpdateTransactionResponse], error)
	DeleteTransaction(context.Context, *connect_go.Request[v1.DeleteTransactionRequest]) (*connect_go.Response[v1.DeleteTransactionResponse], error)
	ListTransactions(context.Context, *connect_go.Request[v1.ListTransactionsRequest]) (*connect_go.Response[v1.ListTransactionsResponse], error)
}

// NewTransactionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTransactionServiceHandler(svc TransactionServiceHandler, opts ...connect_go.HandlerOption) (string, http.Handler) {
	transactionServiceCreateTransactionHandler := connect_go.NewUnaryHandler(
		TransactionServiceCreateTransactionProcedure,
		svc.CreateTransaction,
		opts...,
	)
	transactionServiceGetTransactionHandler := connect_go.NewUnaryHandler(
		TransactionServiceGetTransactionProcedure,
		svc.GetTransaction,
		opts...,
	)
	transactionServiceUpdateTransactionHandler := connect_go.NewUnaryHandler(
		TransactionServiceUpdateTransactionProcedure,
		svc.UpdateTransaction,
		opts...,
	)
	transactionServiceDeleteTransactionHandler := connect_go.NewUnaryHandler(
		TransactionServiceDeleteTransactionProcedure,
		svc.DeleteTransaction,
		opts...,
	)
	transactionServiceListTransactionsHandler := connect_go.NewUnaryHandler(
		TransactionServiceListTransactionsProcedure,
		svc.ListTransactions,
		opts...,
	)
	return "/findiary.v1.TransactionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TransactionServiceCreateTransactionProcedure:
			transactionServiceCreateTransactionHandler.ServeHTTP(w, r)
		case TransactionServiceGetTransactionProcedure:
			transactionServiceGetTransactionHandler.ServeHTTP(w, r)
		case TransactionServiceUpdateTransactionProcedure:
			transactionServiceUpdateTransactionHandler.ServeHTTP(w, r)
		case TransactionServiceDeleteTransactionProcedure:
			transactionServiceDeleteTransactionHandler.ServeHTTP(w, r)
		case TransactionServiceListTransactionsProcedure:
			transactionServiceListTransactionsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTransactionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTransactionServiceHandler struct{}

func (UnimplementedTransactionServiceHandler) CreateTransaction(context.Context, *connect_go.Request[v1.CreateTransactionRequest]) (*connect_go.Response[v1.CreateTransactionResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.TransactionService.CreateTransaction is not implemented"))
}

func (UnimplementedTransactionServiceHandler) GetTransaction(context.Context, *connect_go.Request[v1.GetTransactionRequest]) (*connect_go.Response[v1.GetTransactionResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.TransactionService.GetTransaction is not implemented"))
}

func (UnimplementedTransactionServiceHandler) UpdateTransaction(context.Context, *connect_go.Request[v1.UpdateTransactionRequest]) (*connect_go.Response[v1.UpdateTransactionResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.TransactionService.UpdateTransaction is not implemented"))
}

func (UnimplementedTransactionServiceHandler) DeleteTransaction(context.Context, *connect_go.Request[v1.DeleteTransactionRequest]) (*connect_go.Response[v1.DeleteTransactionResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.TransactionService.DeleteTransaction is not implemented"))
}

func (UnimplementedTransactionServiceHandler) ListTransactions(context.Context, *connect_go.Request[v1.ListTransactionsRequest]) (*connect_go.Response[v1.ListTransactionsResponse], error) {
	return nil, connect_go.NewError(connect_go.CodeUnimplemented, errors.New("findiary.v1.TransactionService.ListTransactions is not implemented"))
}
