// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: findiary/v1/category_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	FamilyId      *string                `protobuf:"bytes,4,opt,name=family_id,json=familyId,proto3,oneof" json:"family_id,omitempty"`
	Icon          *string                `protobuf:"bytes,5,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	Color         *string                `protobuf:"bytes,6,opt,name=color,proto3,oneof" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryRequest) Reset() {
	*x = CreateCategoryRequest{}
	mi := &file_findiary_v1_category_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryRequest) ProtoMessage() {}

func (x *CreateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_category_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryRequest.ProtoReflect.Descriptor instead.
func (*CreateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_category_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCategoryRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateCategoryRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *CreateCategoryRequest) GetFamilyId() string {
	if x != nil && x.FamilyId != nil {
		return *x.FamilyId
	}
	return ""
}

func (x *CreateCategoryRequest) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *CreateCategoryRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

type CreateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCategoryResponse) Reset() {
	*x = CreateCategoryResponse{}
	mi := &file_findiary_v1_category_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCategoryResponse) ProtoMessage() {}

func (x *CreateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_category_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCategoryResponse.ProtoReflect.Descriptor instead.
func (*CreateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_category_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type GetCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryRequest) Reset() {
	*x = GetCategoryRequest{}
	mi := &file_findiary_v1_category_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryRequest) ProtoMessage() {}

func (x *GetCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_category_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryRequest.ProtoReflect.Descriptor instead.
func (*GetCategoryRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_category_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCategoryResponse) Reset() {
	*x = GetCategoryResponse{}
	mi := &file_findiary_v1_category_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCategoryResponse) ProtoMessage() {}

func (x *GetCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_category_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCategoryResponse.ProtoReflect.Descriptor instead.
func (*GetCategoryResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_category_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetCategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type UpdateCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon          *string                `protobuf:"bytes,3,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	Color         *string                `protobuf:"bytes,4,opt,name=color,proto3,oneof" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryRequest) Reset() {
	*x = UpdateCategoryRequest{}
	mi := &file_findiary_v1_category_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryRequest) ProtoMessage() {}

func (x *UpdateCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_category_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateCategoryRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_category_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCategoryRequest) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

func (x *UpdateCategoryRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

type UpdateCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      *Category              `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCategoryResponse) Reset() {
	*x = UpdateCategoryResponse{}
	mi := &file_findiary_v1_category_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCategoryResponse) ProtoMessage() {}

func (x *UpdateCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_category_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCategoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateCategoryResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_category_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateCategoryResponse) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

type DeleteCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryRequest) Reset() {
	*x = DeleteCategoryRequest{}
	mi := &file_findiary_v1_category_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryRequest) ProtoMessage() {}

func (x *DeleteCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_category_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_category_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCategoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryResponse) Reset() {
	*x = DeleteCategoryResponse{}
	mi := &file_findiary_v1_category_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryResponse) ProtoMessage() {}

func (x *DeleteCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_category_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteCategoryResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_category_service_proto_rawDescGZIP(), []int{7}
}

type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scope         string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	FamilyId      *string                `protobuf:"bytes,2,opt,name=family_id,json=familyId,proto3,oneof" json:"family_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_findiary_v1_category_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_category_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_category_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListCategoriesRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ListCategoriesRequest) GetFamilyId() string {
	if x != nil && x.FamilyId != nil {
		return *x.FamilyId
	}
	return ""
}

func (x *ListCategoriesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_findiary_v1_category_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_category_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_category_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_findiary_v1_category_service_proto protoreflect.FileDescriptor

const file_findiary_v1_category_service_proto_rawDesc = "" +
	"\n" +
	"\"findiary/v1/category_service.proto\x12\vfindiary.v1\x1a\x18findiary/v1/common.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xcc\x01\n" +
	"\x15CreateCategoryRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12 \n" +
	"\tfamily_id\x18\x04 \x01(\tH\x00R\bfamilyId\x88\x01\x01\x12\x17\n" +
	"\x04icon\x18\x05 \x01(\tH\x01R\x04icon\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x06 \x01(\tH\x02R\x05color\x88\x01\x01B\f\n" +
	"\n" +
	"_family_idB\a\n" +
	"\x05_iconB\b\n" +
	"\x06_color\"K\n" +
	"\x16CreateCategoryResponse\x121\n" +
	"\bcategory\x18\x01 \x01(\v2\x15.findiary.v1.CategoryR\bcategory\"$\n" +
	"\x12GetCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x13GetCategoryResponse\x121\n" +
	"\bcategory\x18\x01 \x01(\v2\x15.findiary.v1.CategoryR\bcategory\"\x82\x01\n" +
	"\x15UpdateCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x17\n" +
	"\x04icon\x18\x03 \x01(\tH\x00R\x04icon\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x04 \x01(\tH\x01R\x05color\x88\x01\x01B\a\n" +
	"\x05_iconB\b\n" +
	"\x06_color\"K\n" +
	"\x16UpdateCategoryResponse\x121\n" +
	"\bcategory\x18\x01 \x01(\v2\x15.findiary.v1.CategoryR\bcategory\"'\n" +
	"\x15DeleteCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x16DeleteCategoryResponse\"q\n" +
	"\x15ListCategoriesRequest\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12 \n" +
	"\tfamily_id\x18\x02 \x01(\tH\x00R\bfamilyId\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04typeB\f\n" +
	"\n" +
	"_family_id\"O\n" +
	"\x16ListCategoriesResponse\x125\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x15.findiary.v1.CategoryR\n" +
	"categories2\xcf\x03\n" +
	"\x0fCategoryService\x12Y\n" +
	"\x0eCreateCategory\x12\".findiary.v1.CreateCategoryRequest\x1a#.findiary.v1.CreateCategoryResponse\x12P\n" +
	"\vGetCategory\x12\x1f.findiary.v1.GetCategoryRequest\x1a .findiary.v1.GetCategoryResponse\x12Y\n" +
	"\x0eUpdateCategory\x12\".findiary.v1.UpdateCategoryRequest\x1a#.findiary.v1.UpdateCategoryResponse\x12Y\n" +
	"\x0eDeleteCategory\x12\".findiary.v1.DeleteCategoryRequest\x1a#.findiary.v1.DeleteCategoryResponse\x12Y\n" +
	"\x0eListCategories\x12\".findiary.v1.ListCategoriesRequest\x1a#.findiary.v1.ListCategoriesResponseB<Z:github.com/kshku/findiary/backend/internal/api/findiary/v1b\x06proto3"

var (
	file_findiary_v1_category_service_proto_rawDescOnce sync.Once
	file_findiary_v1_category_service_proto_rawDescData []byte
)

func file_findiary_v1_category_service_proto_rawDescGZIP() []byte {
	file_findiary_v1_category_service_proto_rawDescOnce.Do(func() {
		file_findiary_v1_category_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_findiary_v1_category_service_proto_rawDesc), len(file_findiary_v1_category_service_proto_rawDesc)))
	})
	return file_findiary_v1_category_service_proto_rawDescData
}

var file_findiary_v1_category_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_findiary_v1_category_service_proto_goTypes = []any{
	(*CreateCategoryRequest)(nil),  // 0: findiary.v1.CreateCategoryRequest
	(*CreateCategoryResponse)(nil), // 1: findiary.v1.CreateCategoryResponse
	(*GetCategoryRequest)(nil),     // 2: findiary.v1.GetCategoryRequest
	(*GetCategoryResponse)(nil),    // 3: findiary.v1.GetCategoryResponse
	(*UpdateCategoryRequest)(nil),  // 4: findiary.v1.UpdateCategoryRequest
	(*UpdateCategoryResponse)(nil), // 5: findiary.v1.UpdateCategoryResponse
	(*DeleteCategoryRequest)(nil),  // 6: findiary.v1.DeleteCategoryRequest
	(*DeleteCategoryResponse)(nil), // 7: findiary.v1.DeleteCategoryResponse
	(*ListCategoriesRequest)(nil),  // 8: findiary.v1.ListCategoriesRequest
	(*ListCategoriesResponse)(nil), // 9: findiary.v1.ListCategoriesResponse
	(*Category)(nil),               // 10: findiary.v1.Category
}
var file_findiary_v1_category_service_proto_depIdxs = []int32{
	10, // 0: findiary.v1.CreateCategoryResponse.category:type_name -> findiary.v1.Category
	10, // 1: findiary.v1.GetCategoryResponse.category:type_name -> findiary.v1.Category
	10, // 2: findiary.v1.UpdateCategoryResponse.category:type_name -> findiary.v1.Category
	10, // 3: findiary.v1.ListCategoriesResponse.categories:type_name -> findiary.v1.Category
	0,  // 4: findiary.v1.CategoryService.CreateCategory:input_type -> findiary.v1.CreateCategoryRequest
	2,  // 5: findiary.v1.CategoryService.GetCategory:input_type -> findiary.v1.GetCategoryRequest
	4,  // 6: findiary.v1.CategoryService.UpdateCategory:input_type -> findiary.v1.UpdateCategoryRequest
	6,  // 7: findiary.v1.CategoryService.DeleteCategory:input_type -> findiary.v1.DeleteCategoryRequest
	8,  // 8: findiary.v1.CategoryService.ListCategories:input_type -> findiary.v1.ListCategoriesRequest
	1,  // 9: findiary.v1.CategoryService.CreateCategory:output_type -> findiary.v1.CreateCategoryResponse
	3,  // 10: findiary.v1.CategoryService.GetCategory:output_type -> findiary.v1.GetCategoryResponse
	5,  // 11: findiary.v1.CategoryService.UpdateCategory:output_type -> findiary.v1.UpdateCategoryResponse
	7,  // 12: findiary.v1.CategoryService.DeleteCategory:output_type -> findiary.v1.DeleteCategoryResponse
	9,  // 13: findiary.v1.CategoryService.ListCategories:output_type -> findiary.v1.ListCategoriesResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_findiary_v1_category_service_proto_init() }
func file_findiary_v1_category_service_proto_init() {
	if File_findiary_v1_category_service_proto != nil {
		return
	}
	file_findiary_v1_common_proto_init()
	file_findiary_v1_category_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_findiary_v1_category_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_findiary_v1_category_service_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_findiary_v1_category_service_proto_rawDesc), len(file_findiary_v1_category_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_findiary_v1_category_service_proto_goTypes,
		DependencyIndexes: file_findiary_v1_category_service_proto_depIdxs,
		MessageInfos:      file_findiary_v1_category_service_proto_msgTypes,
	}.Build()
	File_findiary_v1_category_service_proto = out.File
	file_findiary_v1_category_service_proto_goTypes = nil
	file_findiary_v1_category_service_proto_depIdxs = nil
}
