// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: findiary/v1/dashboard_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      *string                `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3,oneof" json:"family_id,omitempty"`
	Months        int32                  `protobuf:"varint,2,opt,name=months,proto3" json:"months,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardRequest) Reset() {
	*x = GetDashboardRequest{}
	mi := &file_findiary_v1_dashboard_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardRequest) ProtoMessage() {}

func (x *GetDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_dashboard_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_dashboard_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetDashboardRequest) GetFamilyId() string {
	if x != nil && x.FamilyId != nil {
		return *x.FamilyId
	}
	return ""
}

func (x *GetDashboardRequest) GetMonths() int32 {
	if x != nil {
		return x.Months
	}
	return 0
}

type MonthlySummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	YearMonth     string                 `protobuf:"bytes,1,opt,name=year_month,json=yearMonth,proto3" json:"year_month,omitempty"`
	TotalIncome   float64                `protobuf:"fixed64,2,opt,name=total_income,json=totalIncome,proto3" json:"total_income,omitempty"`
	TotalExpense  float64                `protobuf:"fixed64,3,opt,name=total_expense,json=totalExpense,proto3" json:"total_expense,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonthlySummary) Reset() {
	*x = MonthlySummary{}
	mi := &file_findiary_v1_dashboard_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonthlySummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonthlySummary) ProtoMessage() {}

func (x *MonthlySummary) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_dashboard_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonthlySummary.ProtoReflect.Descriptor instead.
func (*MonthlySummary) Descriptor() ([]byte, []int) {
	return file_findiary_v1_dashboard_service_proto_rawDescGZIP(), []int{1}
}

func (x *MonthlySummary) GetYearMonth() string {
	if x != nil {
		return x.YearMonth
	}
	return ""
}

func (x *MonthlySummary) GetTotalIncome() float64 {
	if x != nil {
		return x.TotalIncome
	}
	return 0
}

func (x *MonthlySummary) GetTotalExpense() float64 {
	if x != nil {
		return x.TotalExpense
	}
	return 0
}

type GetDashboardResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalIncome        float64                `protobuf:"fixed64,1,opt,name=total_income,json=totalIncome,proto3" json:"total_income,omitempty"`
	TotalExpense       float64                `protobuf:"fixed64,2,opt,name=total_expense,json=totalExpense,proto3" json:"total_expense,omitempty"`
	Monthly            []*MonthlySummary      `protobuf:"bytes,3,rep,name=monthly,proto3" json:"monthly,omitempty"`
	RecentTransactions []*Transaction         `protobuf:"bytes,4,rep,name=recent_transactions,json=recentTransactions,proto3" json:"recent_transactions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetDashboardResponse) Reset() {
	*x = GetDashboardResponse{}
	mi := &file_findiary_v1_dashboard_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardResponse) ProtoMessage() {}

func (x *GetDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_dashboard_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_dashboard_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetDashboardResponse) GetTotalIncome() float64 {
	if x != nil {
		return x.TotalIncome
	}
	return 0
}

func (x *GetDashboardResponse) GetTotalExpense() float64 {
	if x != nil {
		return x.TotalExpense
	}
	return 0
}

func (x *GetDashboardResponse) GetMonthly() []*MonthlySummary {
	if x != nil {
		return x.Monthly
	}
	return nil
}

func (x *GetDashboardResponse) GetRecentTransactions() []*Transaction {
	if x != nil {
		return x.RecentTransactions
	}
	return nil
}

var File_findiary_v1_dashboard_service_proto protoreflect.FileDescriptor

const file_findiary_v1_dashboard_service_proto_rawDesc = "" +
	"\n" +
	"#findiary/v1/dashboard_service.proto\x12\vfindiary.v1\x1a\x18findiary/v1/common.proto\"]\n" +
	"\x13GetDashboardRequest\x12 \n" +
	"\tfamily_id\x18\x01 \x01(\tH\x00R\bfamilyId\x88\x01\x01\x12\x16\n" +
	"\x06months\x18\x02 \x01(\x05R\x06monthsB\f\n" +
	"\n" +
	"_family_id\"w\n" +
	"\x0eMonthlySummary\x12\x1d\n" +
	"\n" +
	"year_month\x18\x01 \x01(\tR\tyearMonth\x12!\n" +
	"\ftotal_income\x18\x02 \x01(\x01R\vtotalIncome\x12#\n" +
	"\rtotal_expense\x18\x03 \x01(\x01R\ftotalExpense\"\xe0\x01\n" +
	"\x14GetDashboardResponse\x12!\n" +
	"\ftotal_income\x18\x01 \x01(\x01R\vtotalIncome\x12#\n" +
	"\rtotal_expense\x18\x02 \x01(\x01R\ftotalExpense\x125\n" +
	"\amonthly\x18\x03 \x03(\v2\x1b.findiary.v1.MonthlySummaryR\amonthly\x12I\n" +
	"\x13recent_transactions\x18\x04 \x03(\v2\x18.findiary.v1.TransactionR\x12recentTransactions2g\n" +
	"\x10DashboardService\x12S\n" +
	"\fGetDashboard\x12 .findiary.v1.GetDashboardRequest\x1a!.findiary.v1.GetDashboardResponseB<Z:github.com/kshku/findiary/backend/internal/api/findiary/v1b\x06proto3"

var (
	file_findiary_v1_dashboard_service_proto_rawDescOnce sync.Once
	file_findiary_v1_dashboard_service_proto_rawDescData []byte
)

func file_findiary_v1_dashboard_service_proto_rawDescGZIP() []byte {
	file_findiary_v1_dashboard_service_proto_rawDescOnce.Do(func() {
		file_findiary_v1_dashboard_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_findiary_v1_dashboard_service_proto_rawDesc), len(file_findiary_v1_dashboard_service_proto_rawDesc)))
	})
	return file_findiary_v1_dashboard_service_proto_rawDescData
}

var file_findiary_v1_dashboard_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_findiary_v1_dashboard_service_proto_goTypes = []any{
	(*GetDashboardRequest)(nil),  // 0: findiary.v1.GetDashboardRequest
	(*MonthlySummary)(nil),       // 1: findiary.v1.MonthlySummary
	(*GetDashboardResponse)(nil), // 2: findiary.v1.GetDashboardResponse
	(*Transaction)(nil),          // 3: findiary.v1.Transaction
}
var file_findiary_v1_dashboard_service_proto_depIdxs = []int32{
	1, // 0: findiary.v1.GetDashboardResponse.monthly:type_name -> findiary.v1.MonthlySummary
	3, // 1: findiary.v1.GetDashboardResponse.recent_transactions:type_name -> findiary.v1.Transaction
	0, // 2: findiary.v1.DashboardService.GetDashboard:input_type -> findiary.v1.GetDashboardRequest
	2, // 3: findiary.v1.DashboardService.GetDashboard:output_type -> findiary.v1.GetDashboardResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_findiary_v1_dashboard_service_proto_init() }
func file_findiary_v1_dashboard_service_proto_init() {
	if File_findiary_v1_dashboard_service_proto != nil {
		return
	}
	file_findiary_v1_common_proto_init()
	file_findiary_v1_dashboard_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_findiary_v1_dashboard_service_proto_rawDesc), len(file_findiary_v1_dashboard_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_findiary_v1_dashboard_service_proto_goTypes,
		DependencyIndexes: file_findiary_v1_dashboard_service_proto_depIdxs,
		MessageInfos:      file_findiary_v1_dashboard_service_proto_msgTypes,
	}.Build()
	File_findiary_v1_dashboard_service_proto = out.File
	file_findiary_v1_dashboard_service_proto_goTypes = nil
	file_findiary_v1_dashboard_service_proto_depIdxs = nil
}
