// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: findiary/v1/family_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateFamilyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFamilyRequest) Reset() {
	*x = CreateFamilyRequest{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFamilyRequest) ProtoMessage() {}

func (x *CreateFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFamilyRequest.ProtoReflect.Descriptor instead.
func (*CreateFamilyRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateFamilyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateFamilyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Family        *Family                `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFamilyResponse) Reset() {
	*x = CreateFamilyResponse{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFamilyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFamilyResponse) ProtoMessage() {}

func (x *CreateFamilyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFamilyResponse.ProtoReflect.Descriptor instead.
func (*CreateFamilyResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateFamilyResponse) GetFamily() *Family {
	if x != nil {
		return x.Family
	}
	return nil
}

type GetFamilyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFamilyRequest) Reset() {
	*x = GetFamilyRequest{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFamilyRequest) ProtoMessage() {}

func (x *GetFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFamilyRequest.ProtoReflect.Descriptor instead.
func (*GetFamilyRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetFamilyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetFamilyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Family        *Family                `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFamilyResponse) Reset() {
	*x = GetFamilyResponse{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFamilyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFamilyResponse) ProtoMessage() {}

func (x *GetFamilyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFamilyResponse.ProtoReflect.Descriptor instead.
func (*GetFamilyResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetFamilyResponse) GetFamily() *Family {
	if x != nil {
		return x.Family
	}
	return nil
}

type UpdateFamilyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFamilyRequest) Reset() {
	*x = UpdateFamilyRequest{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFamilyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFamilyRequest) ProtoMessage() {}

func (x *UpdateFamilyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFamilyRequest.ProtoReflect.Descriptor instead.
func (*UpdateFamilyRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateFamilyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFamilyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateFamilyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Family        *Family                `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFamilyResponse) Reset() {
	*x = UpdateFamilyResponse{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFamilyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFamilyResponse) ProtoMessage() {}

func (x *UpdateFamilyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFamilyResponse.ProtoReflect.Descriptor instead.
func (*UpdateFamilyResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateFamilyResponse) GetFamily() *Family {
	if x != nil {
		return x.Family
	}
	return nil
}

type ListMyFamiliesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Families      []*Family              `protobuf:"bytes,1,rep,name=families,proto3" json:"families,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyFamiliesResponse) Reset() {
	*x = ListMyFamiliesResponse{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyFamiliesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyFamiliesResponse) ProtoMessage() {}

func (x *ListMyFamiliesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyFamiliesResponse.ProtoReflect.Descriptor instead.
func (*ListMyFamiliesResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListMyFamiliesResponse) GetFamilies() []*Family {
	if x != nil {
		return x.Families
	}
	return nil
}

type AddMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{7}
}

func (x *AddMemberRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *AddMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AddMemberRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AddMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *FamilyMember          `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberResponse) Reset() {
	*x = AddMemberResponse{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberResponse) ProtoMessage() {}

func (x *AddMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberResponse.ProtoReflect.Descriptor instead.
func (*AddMemberResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{8}
}

func (x *AddMemberResponse) GetMember() *FamilyMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveMemberRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *RemoveMemberRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RemoveMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberResponse) Reset() {
	*x = RemoveMemberResponse{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberResponse) ProtoMessage() {}

func (x *RemoveMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberResponse.ProtoReflect.Descriptor instead.
func (*RemoveMemberResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{10}
}

type InviteMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteMemberRequest) Reset() {
	*x = InviteMemberRequest{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMemberRequest) ProtoMessage() {}

func (x *InviteMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMemberRequest.ProtoReflect.Descriptor instead.
func (*InviteMemberRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{11}
}

func (x *InviteMemberRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

func (x *InviteMemberRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type InviteMemberResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitation    *Invitation            `protobuf:"bytes,1,opt,name=invitation,proto3" json:"invitation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteMemberResponse) Reset() {
	*x = InviteMemberResponse{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteMemberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteMemberResponse) ProtoMessage() {}

func (x *InviteMemberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteMemberResponse.ProtoReflect.Descriptor instead.
func (*InviteMemberResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{12}
}

func (x *InviteMemberResponse) GetInvitation() *Invitation {
	if x != nil {
		return x.Invitation
	}
	return nil
}

type AcceptInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInvitationRequest) Reset() {
	*x = AcceptInvitationRequest{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvitationRequest) ProtoMessage() {}

func (x *AcceptInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvitationRequest.ProtoReflect.Descriptor instead.
func (*AcceptInvitationRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{13}
}

func (x *AcceptInvitationRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type AcceptInvitationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        *FamilyMember          `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptInvitationResponse) Reset() {
	*x = AcceptInvitationResponse{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInvitationResponse) ProtoMessage() {}

func (x *AcceptInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInvitationResponse.ProtoReflect.Descriptor instead.
func (*AcceptInvitationResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{14}
}

func (x *AcceptInvitationResponse) GetMember() *FamilyMember {
	if x != nil {
		return x.Member
	}
	return nil
}

type RevokeInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeInvitationRequest) Reset() {
	*x = RevokeInvitationRequest{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeInvitationRequest) ProtoMessage() {}

func (x *RevokeInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeInvitationRequest.ProtoReflect.Descriptor instead.
func (*RevokeInvitationRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{15}
}

func (x *RevokeInvitationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RevokeInvitationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitation    *Invitation            `protobuf:"bytes,1,opt,name=invitation,proto3" json:"invitation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeInvitationResponse) Reset() {
	*x = RevokeInvitationResponse{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeInvitationResponse) ProtoMessage() {}

func (x *RevokeInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeInvitationResponse.ProtoReflect.Descriptor instead.
func (*RevokeInvitationResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{16}
}

func (x *RevokeInvitationResponse) GetInvitation() *Invitation {
	if x != nil {
		return x.Invitation
	}
	return nil
}

type ListInvitationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvitationsRequest) Reset() {
	*x = ListInvitationsRequest{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitationsRequest) ProtoMessage() {}

func (x *ListInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitationsRequest.ProtoReflect.Descriptor instead.
func (*ListInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{17}
}

func (x *ListInvitationsRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type ListInvitationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitations   []*Invitation          `protobuf:"bytes,1,rep,name=invitations,proto3" json:"invitations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvitationsResponse) Reset() {
	*x = ListInvitationsResponse{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitationsResponse) ProtoMessage() {}

func (x *ListInvitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitationsResponse.ProtoReflect.Descriptor instead.
func (*ListInvitationsResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{18}
}

func (x *ListInvitationsResponse) GetInvitations() []*Invitation {
	if x != nil {
		return x.Invitations
	}
	return nil
}

type ListMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      string                 `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3" json:"family_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersRequest) Reset() {
	*x = ListMembersRequest{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersRequest) ProtoMessage() {}

func (x *ListMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersRequest.ProtoReflect.Descriptor instead.
func (*ListMembersRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{19}
}

func (x *ListMembersRequest) GetFamilyId() string {
	if x != nil {
		return x.FamilyId
	}
	return ""
}

type ListMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*FamilyMember        `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMembersResponse) Reset() {
	*x = ListMembersResponse{}
	mi := &file_findiary_v1_family_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMembersResponse) ProtoMessage() {}

func (x *ListMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_family_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMembersResponse.ProtoReflect.Descriptor instead.
func (*ListMembersResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_family_service_proto_rawDescGZIP(), []int{20}
}

func (x *ListMembersResponse) GetMembers() []*FamilyMember {
	if x != nil {
		return x.Members
	}
	return nil
}

var File_findiary_v1_family_service_proto protoreflect.FileDescriptor

const file_findiary_v1_family_service_proto_rawDesc = "" +
	"\n" +
	" findiary/v1/family_service.proto\x12\vfindiary.v1\x1a\x18findiary/v1/common.proto\x1a\x1bgoogle/protobuf/empty.proto\")\n" +
	"\x13CreateFamilyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"C\n" +
	"\x14CreateFamilyResponse\x12+\n" +
	"\x06family\x18\x01 \x01(\v2\x13.findiary.v1.FamilyR\x06family\"\"\n" +
	"\x10GetFamilyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x11GetFamilyResponse\x12+\n" +
	"\x06family\x18\x01 \x01(\v2\x13.findiary.v1.FamilyR\x06family\"9\n" +
	"\x13UpdateFamilyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"C\n" +
	"\x14UpdateFamilyResponse\x12+\n" +
	"\x06family\x18\x01 \x01(\v2\x13.findiary.v1.FamilyR\x06family\"I\n" +
	"\x16ListMyFamiliesResponse\x12/\n" +
	"\bfamilies\x18\x01 \x03(\v2\x13.findiary.v1.FamilyR\bfamilies\"\\\n" +
	"\x10AddMemberRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\"F\n" +
	"\x11AddMemberResponse\x121\n" +
	"\x06member\x18\x01 \x01(\v2\x19.findiary.v1.FamilyMemberR\x06member\"K\n" +
	"\x13RemoveMemberRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\x16\n" +
	"\x14RemoveMemberResponse\"H\n" +
	"\x13InviteMemberRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\"O\n" +
	"\x14InviteMemberResponse\x127\n" +
	"\n" +
	"invitation\x18\x01 \x01(\v2\x17.findiary.v1.InvitationR\n" +
	"invitation\"-\n" +
	"\x17AcceptInvitationRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"M\n" +
	"\x18AcceptInvitationResponse\x121\n" +
	"\x06member\x18\x01 \x01(\v2\x19.findiary.v1.FamilyMemberR\x06member\")\n" +
	"\x17RevokeInvitationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"S\n" +
	"\x18RevokeInvitationResponse\x127\n" +
	"\n" +
	"invitation\x18\x01 \x01(\v2\x17.findiary.v1.InvitationR\n" +
	"invitation\"5\n" +
	"\x16ListInvitationsRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\"T\n" +
	"\x17ListInvitationsResponse\x129\n" +
	"\vinvitations\x18\x01 \x03(\v2\x17.findiary.v1.InvitationR\vinvitations\"1\n" +
	"\x12ListMembersRequest\x12\x1b\n" +
	"\tfamily_id\x18\x01 \x01(\tR\bfamilyId\"J\n" +
	"\x13ListMembersResponse\x123\n" +
	"\amembers\x18\x01 \x03(\v2\x19.findiary.v1.FamilyMemberR\amembers2\xbc\a\n" +
	"\rFamilyService\x12S\n" +
	"\fCreateFamily\x12 .findiary.v1.CreateFamilyRequest\x1a!.findiary.v1.CreateFamilyResponse\x12J\n" +
	"\tGetFamily\x12\x1d.findiary.v1.GetFamilyRequest\x1a\x1e.findiary.v1.GetFamilyResponse\x12S\n" +
	"\fUpdateFamily\x12 .findiary.v1.UpdateFamilyRequest\x1a!.findiary.v1.UpdateFamilyResponse\x12M\n" +
	"\x0eListMyFamilies\x12\x16.google.protobuf.Empty\x1a#.findiary.v1.ListMyFamiliesResponse\x12J\n" +
	"\tAddMember\x12\x1d.findiary.v1.AddMemberRequest\x1a\x1e.findiary.v1.AddMemberResponse\x12S\n" +
	"\fRemoveMember\x12 .findiary.v1.RemoveMemberRequest\x1a!.findiary.v1.RemoveMemberResponse\x12S\n" +
	"\fInviteMember\x12 .findiary.v1.InviteMemberRequest\x1a!.findiary.v1.InviteMemberResponse\x12_\n" +
	"\x10AcceptInvitation\x12$.findiary.v1.AcceptInvitationRequest\x1a%.findiary.v1.AcceptInvitationResponse\x12_\n" +
	"\x10RevokeInvitation\x12$.findiary.v1.RevokeInvitationRequest\x1a%.findiary.v1.RevokeInvitationResponse\x12\\\n" +
	"\x0fListInvitations\x12#.findiary.v1.ListInvitationsRequest\x1a$.findiary.v1.ListInvitationsResponse\x12P\n" +
	"\vListMembers\x12\x1f.findiary.v1.ListMembersRequest\x1a .findiary.v1.ListMembersResponseB<Z:github.com/kshku/findiary/backend/internal/api/findiary/v1b\x06proto3"

var (
	file_findiary_v1_family_service_proto_rawDescOnce sync.Once
	file_findiary_v1_family_service_proto_rawDescData []byte
)

func file_findiary_v1_family_service_proto_rawDescGZIP() []byte {
	file_findiary_v1_family_service_proto_rawDescOnce.Do(func() {
		file_findiary_v1_family_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_findiary_v1_family_service_proto_rawDesc), len(file_findiary_v1_family_service_proto_rawDesc)))
	})
	return file_findiary_v1_family_service_proto_rawDescData
}

var file_findiary_v1_family_service_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_findiary_v1_family_service_proto_goTypes = []any{
	(*CreateFamilyRequest)(nil),      // 0: findiary.v1.CreateFamilyRequest
	(*CreateFamilyResponse)(nil),     // 1: findiary.v1.CreateFamilyResponse
	(*GetFamilyRequest)(nil),         // 2: findiary.v1.GetFamilyRequest
	(*GetFamilyResponse)(nil),        // 3: findiary.v1.GetFamilyResponse
	(*UpdateFamilyRequest)(nil),      // 4: findiary.v1.UpdateFamilyRequest
	(*UpdateFamilyResponse)(nil),     // 5: findiary.v1.UpdateFamilyResponse
	(*ListMyFamiliesResponse)(nil),   // 6: findiary.v1.ListMyFamiliesResponse
	(*AddMemberRequest)(nil),         // 7: findiary.v1.AddMemberRequest
	(*AddMemberResponse)(nil),        // 8: findiary.v1.AddMemberResponse
	(*RemoveMemberRequest)(nil),      // 9: findiary.v1.RemoveMemberRequest
	(*RemoveMemberResponse)(nil),     // 10: findiary.v1.RemoveMemberResponse
	(*InviteMemberRequest)(nil),      // 11: findiary.v1.InviteMemberRequest
	(*InviteMemberResponse)(nil),     // 12: findiary.v1.InviteMemberResponse
	(*AcceptInvitationRequest)(nil),  // 13: findiary.v1.AcceptInvitationRequest
	(*AcceptInvitationResponse)(nil), // 14: findiary.v1.AcceptInvitationResponse
	(*RevokeInvitationRequest)(nil),  // 15: findiary.v1.RevokeInvitationRequest
	(*RevokeInvitationResponse)(nil), // 16: findiary.v1.RevokeInvitationResponse
	(*ListInvitationsRequest)(nil),   // 17: findiary.v1.ListInvitationsRequest
	(*ListInvitationsResponse)(nil),  // 18: findiary.v1.ListInvitationsResponse
	(*ListMembersRequest)(nil),       // 19: findiary.v1.ListMembersRequest
	(*ListMembersResponse)(nil),      // 20: findiary.v1.ListMembersResponse
	(*Family)(nil),                   // 21: findiary.v1.Family
	(*FamilyMember)(nil),             // 22: findiary.v1.FamilyMember
	(*Invitation)(nil),               // 23: findiary.v1.Invitation
	(*emptypb.Empty)(nil),            // 24: google.protobuf.Empty
}
var file_findiary_v1_family_service_proto_depIdxs = []int32{
	21, // 0: findiary.v1.CreateFamilyResponse.family:type_name -> findiary.v1.Family
	21, // 1: findiary.v1.GetFamilyResponse.family:type_name -> findiary.v1.Family
	21, // 2: findiary.v1.UpdateFamilyResponse.family:type_name -> findiary.v1.Family
	21, // 3: findiary.v1.ListMyFamiliesResponse.families:type_name -> findiary.v1.Family
	22, // 4: findiary.v1.AddMemberResponse.member:type_name -> findiary.v1.FamilyMember
	23, // 5: findiary.v1.InviteMemberResponse.invitation:type_name -> findiary.v1.Invitation
	22, // 6: findiary.v1.AcceptInvitationResponse.member:type_name -> findiary.v1.FamilyMember
	23, // 7: findiary.v1.RevokeInvitationResponse.invitation:type_name -> findiary.v1.Invitation
	23, // 8: findiary.v1.ListInvitationsResponse.invitations:type_name -> findiary.v1.Invitation
	22, // 9: findiary.v1.ListMembersResponse.members:type_name -> findiary.v1.FamilyMember
	0,  // 10: findiary.v1.FamilyService.CreateFamily:input_type -> findiary.v1.CreateFamilyRequest
	2,  // 11: findiary.v1.FamilyService.GetFamily:input_type -> findiary.v1.GetFamilyRequest
	4,  // 12: findiary.v1.FamilyService.UpdateFamily:input_type -> findiary.v1.UpdateFamilyRequest
	24, // 13: findiary.v1.FamilyService.ListMyFamilies:input_type -> google.protobuf.Empty
	7,  // 14: findiary.v1.FamilyService.AddMember:input_type -> findiary.v1.AddMemberRequest
	9,  // 15: findiary.v1.FamilyService.RemoveMember:input_type -> findiary.v1.RemoveMemberRequest
	11, // 16: findiary.v1.FamilyService.InviteMember:input_type -> findiary.v1.InviteMemberRequest
	13, // 17: findiary.v1.FamilyService.AcceptInvitation:input_type -> findiary.v1.AcceptInvitationRequest
	15, // 18: findiary.v1.FamilyService.RevokeInvitation:input_type -> findiary.v1.RevokeInvitationRequest
	17, // 19: findiary.v1.FamilyService.ListInvitations:input_type -> findiary.v1.ListInvitationsRequest
	19, // 20: findiary.v1.FamilyService.ListMembers:input_type -> findiary.v1.ListMembersRequest
	1,  // 21: findiary.v1.FamilyService.CreateFamily:output_type -> findiary.v1.CreateFamilyResponse
	3,  // 22: findiary.v1.FamilyService.GetFamily:output_type -> findiary.v1.GetFamilyResponse
	5,  // 23: findiary.v1.FamilyService.UpdateFamily:output_type -> findiary.v1.UpdateFamilyResponse
	6,  // 24: findiary.v1.FamilyService.ListMyFamilies:output_type -> findiary.v1.ListMyFamiliesResponse
	8,  // 25: findiary.v1.FamilyService.AddMember:output_type -> findiary.v1.AddMemberResponse
	10, // 26: findiary.v1.FamilyService.RemoveMember:output_type -> findiary.v1.RemoveMemberResponse
	12, // 27: findiary.v1.FamilyService.InviteMember:output_type -> findiary.v1.InviteMemberResponse
	14, // 28: findiary.v1.FamilyService.AcceptInvitation:output_type -> findiary.v1.AcceptInvitationResponse
	16, // 29: findiary.v1.FamilyService.RevokeInvitation:output_type -> findiary.v1.RevokeInvitationResponse
	18, // 30: findiary.v1.FamilyService.ListInvitations:output_type -> findiary.v1.ListInvitationsResponse
	20, // 31: findiary.v1.FamilyService.ListMembers:output_type -> findiary.v1.ListMembersResponse
	21, // [21:32] is the sub-list for method output_type
	10, // [10:21] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_findiary_v1_family_service_proto_init() }
func file_findiary_v1_family_service_proto_init() {
	if File_findiary_v1_family_service_proto != nil {
		return
	}
	file_findiary_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_findiary_v1_family_service_proto_rawDesc), len(file_findiary_v1_family_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_findiary_v1_family_service_proto_goTypes,
		DependencyIndexes: file_findiary_v1_family_service_proto_depIdxs,
		MessageInfos:      file_findiary_v1_family_service_proto_msgTypes,
	}.Build()
	File_findiary_v1_family_service_proto = out.File
	file_findiary_v1_family_service_proto_goTypes = nil
	file_findiary_v1_family_service_proto_depIdxs = nil
}
