// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: findiary/v1/sync_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ScopeId        string                 `protobuf:"bytes,1,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	ScopeType      string                 `protobuf:"bytes,2,opt,name=scope_type,json=scopeType,proto3" json:"scope_type,omitempty"`
	LastCheckpoint int64                  `protobuf:"varint,3,opt,name=last_checkpoint,json=lastCheckpoint,proto3" json:"last_checkpoint,omitempty"`
	LocalChanges   []*SyncChangeEntry     `protobuf:"bytes,4,rep,name=local_changes,json=localChanges,proto3" json:"local_changes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_findiary_v1_sync_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_sync_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_sync_service_proto_rawDescGZIP(), []int{0}
}

func (x *SyncRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *SyncRequest) GetScopeType() string {
	if x != nil {
		return x.ScopeType
	}
	return ""
}

func (x *SyncRequest) GetLastCheckpoint() int64 {
	if x != nil {
		return x.LastCheckpoint
	}
	return 0
}

func (x *SyncRequest) GetLocalChanges() []*SyncChangeEntry {
	if x != nil {
		return x.LocalChanges
	}
	return nil
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewCheckpoint int64                  `protobuf:"varint,1,opt,name=new_checkpoint,json=newCheckpoint,proto3" json:"new_checkpoint,omitempty"`
	RemoteChanges []*SyncChangeEntry     `protobuf:"bytes,2,rep,name=remote_changes,json=remoteChanges,proto3" json:"remote_changes,omitempty"`
	Conflicts     []*ConflictInfo        `protobuf:"bytes,3,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_findiary_v1_sync_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_sync_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_sync_service_proto_rawDescGZIP(), []int{1}
}

func (x *SyncResponse) GetNewCheckpoint() int64 {
	if x != nil {
		return x.NewCheckpoint
	}
	return 0
}

func (x *SyncResponse) GetRemoteChanges() []*SyncChangeEntry {
	if x != nil {
		return x.RemoteChanges
	}
	return nil
}

func (x *SyncResponse) GetConflicts() []*ConflictInfo {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

type SyncChangeEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EntityType      string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId        string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Action          string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Snapshot        []byte                 `protobuf:"bytes,4,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	ClientTimestamp *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"`
	ChangedFields   []string               `protobuf:"bytes,6,rep,name=changed_fields,json=changedFields,proto3" json:"changed_fields,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncChangeEntry) Reset() {
	*x = SyncChangeEntry{}
	mi := &file_findiary_v1_sync_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncChangeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncChangeEntry) ProtoMessage() {}

func (x *SyncChangeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_sync_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncChangeEntry.ProtoReflect.Descriptor instead.
func (*SyncChangeEntry) Descriptor() ([]byte, []int) {
	return file_findiary_v1_sync_service_proto_rawDescGZIP(), []int{2}
}

func (x *SyncChangeEntry) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *SyncChangeEntry) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *SyncChangeEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *SyncChangeEntry) GetSnapshot() []byte {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *SyncChangeEntry) GetClientTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ClientTimestamp
	}
	return nil
}

func (x *SyncChangeEntry) GetChangedFields() []string {
	if x != nil {
		return x.ChangedFields
	}
	return nil
}

type ConflictInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityType    string                 `protobuf:"bytes,1,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Field         string                 `protobuf:"bytes,3,opt,name=field,proto3" json:"field,omitempty"`
	LocalValue    string                 `protobuf:"bytes,4,opt,name=local_value,json=localValue,proto3" json:"local_value,omitempty"`
	ServerValue   string                 `protobuf:"bytes,5,opt,name=server_value,json=serverValue,proto3" json:"server_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConflictInfo) Reset() {
	*x = ConflictInfo{}
	mi := &file_findiary_v1_sync_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConflictInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConflictInfo) ProtoMessage() {}

func (x *ConflictInfo) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_sync_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConflictInfo.ProtoReflect.Descriptor instead.
func (*ConflictInfo) Descriptor() ([]byte, []int) {
	return file_findiary_v1_sync_service_proto_rawDescGZIP(), []int{3}
}

func (x *ConflictInfo) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *ConflictInfo) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ConflictInfo) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ConflictInfo) GetLocalValue() string {
	if x != nil {
		return x.LocalValue
	}
	return ""
}

func (x *ConflictInfo) GetServerValue() string {
	if x != nil {
		return x.ServerValue
	}
	return ""
}

var File_findiary_v1_sync_service_proto protoreflect.FileDescriptor

const file_findiary_v1_sync_service_proto_rawDesc = "" +
	"\n" +
	"\x1efindiary/v1/sync_service.proto\x12\vfindiary.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x01\n" +
	"\vSyncRequest\x12\x19\n" +
	"\bscope_id\x18\x01 \x01(\tR\ascopeId\x12\x1d\n" +
	"\n" +
	"scope_type\x18\x02 \x01(\tR\tscopeType\x12'\n" +
	"\x0flast_checkpoint\x18\x03 \x01(\x03R\x0elastCheckpoint\x12A\n" +
	"\rlocal_changes\x18\x04 \x03(\v2\x1c.findiary.v1.SyncChangeEntryR\flocalChanges\"\xb3\x01\n" +
	"\fSyncResponse\x12%\n" +
	"\x0enew_checkpoint\x18\x01 \x01(\x03R\rnewCheckpoint\x12C\n" +
	"\x0eremote_changes\x18\x02 \x03(\v2\x1c.findiary.v1.SyncChangeEntryR\rremoteChanges\x127\n" +
	"\tconflicts\x18\x03 \x03(\v2\x19.findiary.v1.ConflictInfoR\tconflicts\"\xf1\x01\n" +
	"\x0fSyncChangeEntry\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1a\n" +
	"\bsnapshot\x18\x04 \x01(\fR\bsnapshot\x12E\n" +
	"\x10client_timestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x0fclientTimestamp\x12%\n" +
	"\x0echanged_fields\x18\x06 \x03(\tR\rchangedFields\"\xa6\x01\n" +
	"\fConflictInfo\x12\x1f\n" +
	"\ventity_type\x18\x01 \x01(\tR\n" +
	"entityType\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x14\n" +
	"\x05field\x18\x03 \x01(\tR\x05field\x12\x1f\n" +
	"\vlocal_value\x18\x04 \x01(\tR\n" +
	"localValue\x12!\n" +
	"\fserver_value\x18\x05 \x01(\tR\vserverValue2J\n" +
	"\vSyncService\x12;\n" +
	"\x04Sync\x12\x18.findiary.v1.SyncRequest\x1a\x19.findiary.v1.SyncResponseB<Z:github.com/kshku/findiary/backend/internal/api/findiary/v1b\x06proto3"

var (
	file_findiary_v1_sync_service_proto_rawDescOnce sync.Once
	file_findiary_v1_sync_service_proto_rawDescData []byte
)

func file_findiary_v1_sync_service_proto_rawDescGZIP() []byte {
	file_findiary_v1_sync_service_proto_rawDescOnce.Do(func() {
		file_findiary_v1_sync_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_findiary_v1_sync_service_proto_rawDesc), len(file_findiary_v1_sync_service_proto_rawDesc)))
	})
	return file_findiary_v1_sync_service_proto_rawDescData
}

var file_findiary_v1_sync_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_findiary_v1_sync_service_proto_goTypes = []any{
	(*SyncRequest)(nil),           // 0: findiary.v1.SyncRequest
	(*SyncResponse)(nil),          // 1: findiary.v1.SyncResponse
	(*SyncChangeEntry)(nil),       // 2: findiary.v1.SyncChangeEntry
	(*ConflictInfo)(nil),          // 3: findiary.v1.ConflictInfo
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_findiary_v1_sync_service_proto_depIdxs = []int32{
	2, // 0: findiary.v1.SyncRequest.local_changes:type_name -> findiary.v1.SyncChangeEntry
	2, // 1: findiary.v1.SyncResponse.remote_changes:type_name -> findiary.v1.SyncChangeEntry
	3, // 2: findiary.v1.SyncResponse.conflicts:type_name -> findiary.v1.ConflictInfo
	4, // 3: findiary.v1.SyncChangeEntry.client_timestamp:type_name -> google.protobuf.Timestamp
	0, // 4: findiary.v1.SyncService.Sync:input_type -> findiary.v1.SyncRequest
	1, // 5: findiary.v1.SyncService.Sync:output_type -> findiary.v1.SyncResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_findiary_v1_sync_service_proto_init() }
func file_findiary_v1_sync_service_proto_init() {
	if File_findiary_v1_sync_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_findiary_v1_sync_service_proto_rawDesc), len(file_findiary_v1_sync_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_findiary_v1_sync_service_proto_goTypes,
		DependencyIndexes: file_findiary_v1_sync_service_proto_depIdxs,
		MessageInfos:      file_findiary_v1_sync_service_proto_msgTypes,
	}.Build()
	File_findiary_v1_sync_service_proto = out.File
	file_findiary_v1_sync_service_proto_goTypes = nil
	file_findiary_v1_sync_service_proto_depIdxs = nil
}
