// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: findiary/v1/transaction_service.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      *string                `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3,oneof" json:"family_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	CategoryId    string                 `protobuf:"bytes,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Description   *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Date          string                 `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_findiary_v1_transaction_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_transaction_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_transaction_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTransactionRequest) GetFamilyId() string {
	if x != nil && x.FamilyId != nil {
		return *x.FamilyId
	}
	return ""
}

func (x *CreateTransactionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateTransactionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateTransactionRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CreateTransactionRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *CreateTransactionRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type CreateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_findiary_v1_transaction_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_transaction_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_transaction_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_findiary_v1_transaction_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_transaction_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_transaction_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_findiary_v1_transaction_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_transaction_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_transaction_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type UpdateTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	CategoryId    string                 `protobuf:"bytes,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Description   *string                `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Date          string                 `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransactionRequest) Reset() {
	*x = UpdateTransactionRequest{}
	mi := &file_findiary_v1_transaction_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionRequest) ProtoMessage() {}

func (x *UpdateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_transaction_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_transaction_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTransactionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateTransactionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *UpdateTransactionRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *UpdateTransactionRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateTransactionRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type UpdateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransactionResponse) Reset() {
	*x = UpdateTransactionResponse{}
	mi := &file_findiary_v1_transaction_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionResponse) ProtoMessage() {}

func (x *UpdateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_transaction_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionResponse.ProtoReflect.Descriptor instead.
func (*UpdateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_transaction_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type DeleteTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionRequest) Reset() {
	*x = DeleteTransactionRequest{}
	mi := &file_findiary_v1_transaction_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionRequest) ProtoMessage() {}

func (x *DeleteTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_transaction_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransactionRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_transaction_service_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTransactionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionResponse) Reset() {
	*x = DeleteTransactionResponse{}
	mi := &file_findiary_v1_transaction_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionResponse) ProtoMessage() {}

func (x *DeleteTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_transaction_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionResponse.ProtoReflect.Descriptor instead.
func (*DeleteTransactionResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_transaction_service_proto_rawDescGZIP(), []int{7}
}

type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FamilyId      *string                `protobuf:"bytes,1,opt,name=family_id,json=familyId,proto3,oneof" json:"family_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	CategoryId    string                 `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     int32                  `protobuf:"varint,7,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_findiary_v1_transaction_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_transaction_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_findiary_v1_transaction_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListTransactionsRequest) GetFamilyId() string {
	if x != nil && x.FamilyId != nil {
		return *x.FamilyId
	}
	return ""
}

func (x *ListTransactionsRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ListTransactionsRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ListTransactionsRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ListTransactionsRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

func (x *ListTransactionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTransactionsRequest) GetPageToken() int32 {
	if x != nil {
		return x.PageToken
	}
	return 0
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	NextPageToken int32                  `protobuf:"varint,3,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_findiary_v1_transaction_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_findiary_v1_transaction_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_findiary_v1_transaction_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListTransactionsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTransactionsResponse) GetNextPageToken() int32 {
	if x != nil {
		return x.NextPageToken
	}
	return 0
}

var File_findiary_v1_transaction_service_proto protoreflect.FileDescriptor

const file_findiary_v1_transaction_service_proto_rawDesc = "" +
	"\n" +
	"%findiary/v1/transaction_service.proto\x12\vfindiary.v1\x1a\x18findiary/v1/common.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xfe\x01\n" +
	"\x18CreateTransactionRequest\x12 \n" +
	"\tfamily_id\x18\x01 \x01(\tH\x00R\bfamilyId\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\tR\n" +
	"categoryId\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x12\n" +
	"\x04date\x18\a \x01(\tR\x04dateB\f\n" +
	"\n" +
	"_family_idB\x0e\n" +
	"\f_description\"W\n" +
	"\x19CreateTransactionResponse\x12:\n" +
	"\vtransaction\x18\x01 \x01(\v2\x18.findiary.v1.TransactionR\vtransaction\"'\n" +
	"\x15GetTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"T\n" +
	"\x16GetTransactionResponse\x12:\n" +
	"\vtransaction\x18\x01 \x01(\v2\x18.findiary.v1.TransactionR\vtransaction\"\xde\x01\n" +
	"\x18UpdateTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\tR\n" +
	"categoryId\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x12\n" +
	"\x04date\x18\a \x01(\tR\x04dateB\x0e\n" +
	"\f_description\"W\n" +
	"\x19UpdateTransactionResponse\x12:\n" +
	"\vtransaction\x18\x01 \x01(\v2\x18.findiary.v1.TransactionR\vtransaction\"*\n" +
	"\x18DeleteTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1b\n" +
	"\x19DeleteTransactionResponse\"\xf4\x01\n" +
	"\x17ListTransactionsRequest\x12 \n" +
	"\tfamily_id\x18\x01 \x01(\tH\x00R\bfamilyId\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\tR\n" +
	"categoryId\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\a \x01(\x05R\tpageTokenB\f\n" +
	"\n" +
	"_family_id\"\x96\x01\n" +
	"\x18ListTransactionsResponse\x12<\n" +
	"\ftransactions\x18\x01 \x03(\v2\x18.findiary.v1.TransactionR\ftransactions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12&\n" +
	"\x0fnext_page_token\x18\x03 \x01(\x05R\rnextPageToken2\xfc\x03\n" +
	"\x12TransactionService\x12b\n" +
	"\x11CreateTransaction\x12%.findiary.v1.CreateTransactionRequest\x1a&.findiary.v1.CreateTransactionResponse\x12Y\n" +
	"\x0eGetTransaction\x12\".findiary.v1.GetTransactionRequest\x1a#.findiary.v1.GetTransactionResponse\x12b\n" +
	"\x11UpdateTransaction\x12%.findiary.v1.UpdateTransactionRequest\x1a&.findiary.v1.UpdateTransactionResponse\x12b\n" +
	"\x11DeleteTransaction\x12%.findiary.v1.DeleteTransactionRequest\x1a&.findiary.v1.DeleteTransactionResponse\x12_\n" +
	"\x10ListTransactions\x12$.findiary.v1.ListTransactionsRequest\x1a%.findiary.v1.ListTransactionsResponseB<Z:github.com/kshku/findiary/backend/internal/api/findiary/v1b\x06proto3"

var (
	file_findiary_v1_transaction_service_proto_rawDescOnce sync.Once
	file_findiary_v1_transaction_service_proto_rawDescData []byte
)

func file_findiary_v1_transaction_service_proto_rawDescGZIP() []byte {
	file_findiary_v1_transaction_service_proto_rawDescOnce.Do(func() {
		file_findiary_v1_transaction_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_findiary_v1_transaction_service_proto_rawDesc), len(file_findiary_v1_transaction_service_proto_rawDesc)))
	})
	return file_findiary_v1_transaction_service_proto_rawDescData
}

var file_findiary_v1_transaction_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_findiary_v1_transaction_service_proto_goTypes = []any{
	(*CreateTransactionRequest)(nil),  // 0: findiary.v1.CreateTransactionRequest
	(*CreateTransactionResponse)(nil), // 1: findiary.v1.CreateTransactionResponse
	(*GetTransactionRequest)(nil),     // 2: findiary.v1.GetTransactionRequest
	(*GetTransactionResponse)(nil),    // 3: findiary.v1.GetTransactionResponse
	(*UpdateTransactionRequest)(nil),  // 4: findiary.v1.UpdateTransactionRequest
	(*UpdateTransactionResponse)(nil), // 5: findiary.v1.UpdateTransactionResponse
	(*DeleteTransactionRequest)(nil),  // 6: findiary.v1.DeleteTransactionRequest
	(*DeleteTransactionResponse)(nil), // 7: findiary.v1.DeleteTransactionResponse
	(*ListTransactionsRequest)(nil),   // 8: findiary.v1.ListTransactionsRequest
	(*ListTransactionsResponse)(nil),  // 9: findiary.v1.ListTransactionsResponse
	(*Transaction)(nil),               // 10: findiary.v1.Transaction
}
var file_findiary_v1_transaction_service_proto_depIdxs = []int32{
	10, // 0: findiary.v1.CreateTransactionResponse.transaction:type_name -> findiary.v1.Transaction
	10, // 1: findiary.v1.GetTransactionResponse.transaction:type_name -> findiary.v1.Transaction
	10, // 2: findiary.v1.UpdateTransactionResponse.transaction:type_name -> findiary.v1.Transaction
	10, // 3: findiary.v1.ListTransactionsResponse.transactions:type_name -> findiary.v1.Transaction
	0,  // 4: findiary.v1.TransactionService.CreateTransaction:input_type -> findiary.v1.CreateTransactionRequest
	2,  // 5: findiary.v1.TransactionService.GetTransaction:input_type -> findiary.v1.GetTransactionRequest
	4,  // 6: findiary.v1.TransactionService.UpdateTransaction:input_type -> findiary.v1.UpdateTransactionRequest
	6,  // 7: findiary.v1.TransactionService.DeleteTransaction:input_type -> findiary.v1.DeleteTransactionRequest
	8,  // 8: findiary.v1.TransactionService.ListTransactions:input_type -> findiary.v1.ListTransactionsRequest
	1,  // 9: findiary.v1.TransactionService.CreateTransaction:output_type -> findiary.v1.CreateTransactionResponse
	3,  // 10: findiary.v1.TransactionService.GetTransaction:output_type -> findiary.v1.GetTransactionResponse
	5,  // 11: findiary.v1.TransactionService.UpdateTransaction:output_type -> findiary.v1.UpdateTransactionResponse
	7,  // 12: findiary.v1.TransactionService.DeleteTransaction:output_type -> findiary.v1.DeleteTransactionResponse
	9,  // 13: findiary.v1.TransactionService.ListTransactions:output_type -> findiary.v1.ListTransactionsResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_findiary_v1_transaction_service_proto_init() }
func file_findiary_v1_transaction_service_proto_init() {
	if File_findiary_v1_transaction_service_proto != nil {
		return
	}
	file_findiary_v1_common_proto_init()
	file_findiary_v1_transaction_service_proto_msgTypes[0].OneofWrappers = []any{}
	file_findiary_v1_transaction_service_proto_msgTypes[4].OneofWrappers = []any{}
	file_findiary_v1_transaction_service_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_findiary_v1_transaction_service_proto_rawDesc), len(file_findiary_v1_transaction_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_findiary_v1_transaction_service_proto_goTypes,
		DependencyIndexes: file_findiary_v1_transaction_service_proto_depIdxs,
		MessageInfos:      file_findiary_v1_transaction_service_proto_msgTypes,
	}.Build()
	File_findiary_v1_transaction_service_proto = out.File
	file_findiary_v1_transaction_service_proto_goTypes = nil
	file_findiary_v1_transaction_service_proto_depIdxs = nil
}
